emergency_assistance:
  title: Emergency Assistance
  card_image:
  card_body: We offer best-effort assistance in any emergency you may have. Click above to learn more. Call *9999 24/7 in HCMC if you are experiencing an immediate medical emergency.
  page_link: /emergency-assistance/
arrival_packages:
  title: Arrival Packages
  card_image:
  card_body: We have a number of all-inclusive packages to help you enjoy Vietnam to the fullest!
  page_link: /pricing/
airport_pickup_dropoff:
  title: Airport Pickup / Dropoff
  card_image:
  card_body: Your personal concierge will be there at the airport to welcome you to Vietnam and transport you to your accomodation safely.
  page_link: /airport-pickup-dropoff/
accomodation_search:
  title: Accomodation Search
  card_image:
  card_body:
  page_link:
motorbike_rental:
  title: Motorbike Rental
  card_image:
  card_body:
  page_link:
storage:
  title: Storage
  card_image:
  card_body:
  page_link:
visa_services:
  title: Visa Services
  card_image:
  card_body:
  page_link:
driving_license:
  title: Driving License
  card_image:
  card_body:
  page_link:
personal_assistance:
  title: Personal Assistance
  card_image:
  card_body:
  page_link:
business_assistance:
  title: Business Assistance
  card_image:
  card_body:
  page_link:
bank_accounts:
  title: Bank Account Setup
  card_image:
  card_body:
  page_link:
orientation_tours:
  title: Orientation Tour
  card_image:
  card_body:
  page_link:
moving_services:
  title: Moving Services
  card_image:
  card_body:
  page_link:
cleaning_services:
  title: Cleaning Services
  card_image:
  card_body:
  page_link:
air_purifier_sales:
  title: Air Purifier Sales
  card_image:
  card_body:
  page_link:
gift_delivery_service:
  title: Gift Delivery Services
  card_image:
  card_body:
  page_link:
pest_prevention_service:
  title: Pest Prevention Services
  card_image:
  card_body:
  page_link:
career_counseling:
  title: Career Counseling
  card_image:
  card_body:
  page_link:
register_mobile_phone:
  title: Mobile Phone Registration
  card_image:
  card_body:
  page_link:
marriage_license_assistance:
  title: Marriage License Assistance
  card_image:
  card_body:
  page_link:
laundry_dry_clean_tailor:
  title: Laundry / Dry Cleaning / Tailor Services
  card_image:
  card_body:
  page_link:
car_rental:
  title: Car Rental
  card_image:
  card_body:
  page_link:
interpretation:
  title: Interpretation Services
  card_image:
  card_body:
  page_link:
language_classes:
  title: Language Classes
  card_image:
  card_body:
  page_link:
trip_planning_booking:
  title: Trip Planning / Booking Services
  card_image:
  card_body:
  page_link:
materials_sourcing:
  title: Materials Sourcing
  card_image:
  card_body:
  page_link:
long_term_lease_negotiation:
  title: Long Term Lease Negotiation
  card_image:
  card_body:
  page_link:
water_delivery_setup:
  title: Materials Sourcing
  card_image:
  card_body:
  page_link: